name: Test CodeQL Advanced
run-name: Test CodeQL by @${{ github.actor }}

on:
    workflow_dispatch:
    push:
        branches:
          - dev
          - qat
          - main
          - qa       

permissions:
  id-token: write
  contents: read
  actions: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7

    # - name: Init CodeQL
    #   uses: github/codeql-action/init@v3
    #   with:
    #     languages: java-kotlin
    #     build-mode: manual

    - name: install JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build app ab
      run: mvn clean install -DskipTests
      working-directory: ./ab

    - name: Build app cd
      run: mvn clean install -DskipTests
      working-directory: ./cd

    - name: Print available artifacts
      run: |
        echo "Listing artifacts in the current directory:"
        ls -R
        
        echo "Listing artifacts in the GITHUB_WORKSPACE directory:"
        ls -R $GITHUB_WORKSPACE
        
        echo "Listing all environment variables:"
        env
        
        echo "Listing contents of the GitHub Actions artifact directory:"
        ls -R $GITHUB_WORKSPACE/artifact

    # - name: Run CodeQL
    #   uses: github/codeql-action/analyze@v3
    #   with:
    #     category: "/language:java-kotlin"

    
