name: Test CodeQL
run-name: Test CodeQL by @${{ github.actor }}

on:
    workflow_dispatch:
    push:
        branches:
          - dev
          - qat
          - main
          - qa       

permissions:
  id-token: write
  contents: read
  actions: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Init CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java
        build-mode: manual

    - name: install JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build app
      run: mvn clean install -DskipTests
      working-directory: ./

    - name: Run CodeQL
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:java"

    
