# .github/workflows/deploy.yml
name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  get-jobs:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          JOBS=$(ls glue-jobs | jq -R -s -c 'split("\n")[:-1] | map({
            job_name: ., 
            template_path: ("glue-jobs/" + . + "/template.yaml")
          })')
          echo "matrix={\"include\":$JOBS}" >> $GITHUB_OUTPUT

  deploy-dev:
    needs: get-jobs
    strategy:
      matrix: ${{ fromJson(needs.get-jobs.outputs.matrix) }}
    uses: ./.github/workflows/reusable-cfn-deploy.yml
    with:
      environment: dev
      region: us-east-1
      template_path: ${{ matrix.template_path }}
      stack_name: dev-${{ matrix.job_name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-prod:
    needs: [get-jobs, deploy-dev]
    strategy:
      matrix: ${{ fromJson(needs.get-jobs.outputs.matrix) }}
    uses: ./.github/workflows/reusable-cfn-deploy.yml
    with:
      environment: prod
      region: us-east-1
      template_path: ${{ matrix.template_path }}
      stack_name: prod-${{ matrix.job_name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


