name: ECS Rollback

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'ECS Service to rollback'
        required: true
        type: choice
        options:
          - all
          - service1
          - service2
          - service3
          - service4

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Set up services to rollback
        id: set_services
        run: |
          if [ "${{ github.event.inputs.service }}" == "all" ]; then
            echo "::set-output name=services::service1,service2,service3,service4"
          else
            echo "::set-output name=services::${{ github.event.inputs.service }}"
          fi

      - name: Rollback ECS Services
        run: |
          for service in ${{ steps.set_services.outputs.services }}; do
            echo "Rolling back $service"
            # Add your ECS rollback command here
          done
