name: Service Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_scope:
        description: 'Deployment scope (all or single)'
        required: true
        default: 'single'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [ "${{ github.event.inputs.deploy_scope }}" == "all" ]; then
            echo "matrix={\"service\":[\"service1\",\"service2\",\"service3\",\"service4\"]}" >> $GITHUB_OUTPUT
          else
            echo "matrix={\"service\":[\"service1\"]}" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy ${{ matrix.service }}
        run: |
          echo "Deploying ${{ matrix.service }}"
          # Add your deployment steps here
