name: Service Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_scope:
        description: 'Deployment scope (all or service name)'
        required: true
        default: 'service1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(github.event.inputs.deploy_scope == 'all' && '["service1", "service2", "service3", "service4"]' || format('[ "{0}" ]', github.event.inputs.deploy_scope)) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy ${{ matrix.service }}
        run: |
          echo "Deploying ${{ matrix.service }}"
          # Add your deployment steps here
