name: ECS Rollback

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'ECS Service to rollback'
        required: true
        type: choice
        options:
          - all
          - service1
          - service2
          - service3
          - service4

jobs:
  rollback:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(github.event.inputs.service == 'all' && '["service1", "service2", "service3", "service4"]' || json.dumps([github.event.inputs.service])) }}
      fail-fast: false
    steps:
      - name: Rollback ECS Service
        run: echo "Rolling back ${{ matrix.service }}"
       
