name: rollback pipeline
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (e.g., dev, staging, prod)'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      service:
        description: 'ECS Service to rollback'
        required: true
        type: choice
        options:
          - all
          - service1
          - service2
          - service3
          - service4
          # Add more services as needed

jobs:
  rollback-service:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(github.event.inputs.service == 'all' && '["service1", "service2", "service3", "service4"]' || format('[ "{0}" ]', github.event.inputs.service)) }}

    steps:
      - name: Rollback ECS Service
        run: |
          service_name="demo-ecs-${{ matrix.service }}"
          cluster_name="${service_name}-${{ github.event.inputs.environment }}-cluster"
          echo "Rolling back service $service_name in cluster $cluster_name"
          echo "command executed successfully"
  
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: sangam-kushwaha
          minimum-approvals: 1


