name: CloudFormation Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main    # or 'master' depending on your default branch name
    paths:
      - '**.yaml'
      - '**.yml'
      - '**.json'

jobs:
  cfn-lint:
    name: CFN Lint Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cfn-lint
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint

      - name: Run CloudFormation Linting
        run: |
          echo "Checking CloudFormation templates in PR from ${{ github.head_ref }} to main branch"
          cfn-lint **/*.{yaml,yml,json}
        continue-on-error: false
