name: CloudFormation Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main    # or 'master' depending on your default branch name
    paths:
      - '**.yaml'
      - '**.yml'
      - '**.json'

jobs:
  cfn-lint:
    name: CFN Lint Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install cfn-lint
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint

      - name: Run CloudFormation Linting
        run: |
          echo "Checking CloudFormation templates in PR from ${{ github.head_ref }} to main branch"
          files=$(find . -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) -not -path "./.github/*")
          echo "Files to be scanned:"
          echo "$files"
          echo "-------------------"
          cfn-lint $files
        continue-on-error: false

  cfn-nag:
    name: CFN Nag Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install cfn_nag
        run: |
          gem install cfn-nag

      - name: Run CFN-Nag
        uses: stelligent/cfn_nag@master
        with:
          input_path: .
          extra_args: --fail-on-warnings

      # - name: Run CFN Nag Scan
      #   run: |
      #     echo "Running CFN Nag scan on templates from ${{ github.head_ref }} to main branch"
      #     files=$(find . -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) -not -path "./.github/*")
      #     echo "Files to be scanned:"
      #     echo "$files"
      #     cfn_nag_scan --input-path $files
      #   continue-on-error: false



