# .github/workflows/reusable-cfn-deploy.yml
name: Reusable CFN Deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Deployment environment (dev/prod)"
      region:
        required: true
        type: string
        description: "AWS region for deployment"
        default: "us-east-1"
      template_path:
        required: true
        type: string
        description: "Path to CloudFormation template"
      stack_name:
        required: true
        type: string
        description: "Name of the CloudFormation stack"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Get Stack Info
        run: |
          echo "Environment: ${{inputs.environment}}"
          echo "region: ${{inputs.region}}"
          echo "template_path: ${{inputs.template_path}}"
          echo "stack_name: ${{inputs.stack_name}}"
    
